
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Tue Apr 17 10:19:24 EDT 2001
//----------------------------------------------------

package org.apache.xalan.xsltc.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Literal = 26;
  public static final int GE = 21;
  public static final int NAMESPACE = 47;
  public static final int SLASH = 2;
  public static final int PI = 35;
  public static final int COMMENT = 34;
  public static final int FOLLOWINGSIBLING = 46;
  public static final int ATSIGN = 12;
  public static final int DSLASH = 15;
  public static final int LPAREN = 7;
  public static final int EXPRESSION = 52;
  public static final int INT = 50;
  public static final int CHILD = 39;
  public static final int MINUS = 23;
  public static final int STAR = 9;
  public static final int DESCENDANTORSELF = 44;
  public static final int RPAREN = 8;
  public static final int AND = 33;
  public static final int LT = 18;
  public static final int OR = 32;
  public static final int COMMA = 10;
  public static final int DDOT = 13;
  public static final int DIV = 24;
  public static final int PLUS = 22;
  public static final int DOT = 3;
  public static final int ID = 28;
  public static final int LE = 20;
  public static final int QNAME = 27;
  public static final int DESCENDANT = 43;
  public static final int PRECEDINGSIBLING = 36;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SELF = 37;
  public static final int VBAR = 6;
  public static final int MOD = 25;
  public static final int ANCESTORORSELF = 42;
  public static final int PRECEDING = 48;
  public static final int EQ = 16;
  public static final int PATTERN = 51;
  public static final int LBRACK = 4;
  public static final int REAL = 49;
  public static final int ANCESTOR = 41;
  public static final int RBRACK = 5;
  public static final int DCOLON = 14;
  public static final int DOLLAR = 11;
  public static final int NE = 17;
  public static final int PARENT = 38;
  public static final int FOLLOWING = 45;
  public static final int KEY = 29;
  public static final int TEXT = 30;
  public static final int ATTRIBUTE = 40;
  public static final int GT = 19;
  public static final int NODE = 31;
}

