/* Generated By:JJTree: Do not edit this line. C:/data/projects/xpathapi/xpath-src\XPathTreeConstants.java */

package org.apache.xpath.rwapi.impl.parser;

public interface XPathTreeConstants
{
  public int JJTXPATH2 = 0;
  public int JJTMATCHPATTERN = 1;
  public int JJTXPATH = 2;
  public int JJTEXPRSEQUENCE = 3;
  public int JJTPATTERN = 4;
  public int JJTPATHPATTERN = 5;
  public int JJTROOT = 6;
  public int JJTROOTDESCENDANTS = 7;
  public int JJTSLASH = 8;
  public int JJTSLASHSLASH = 9;
  public int JJTVOID = 10;
  public int JJTPATTERNSTEP = 11;
  public int JJTAXISCHILD = 12;
  public int JJTAXISATTRIBUTE = 13;
  public int JJTAT = 14;
  public int JJTIDKEYPATTERN = 15;
  public int JJTQNAMELPAR = 16;
  public int JJTSTRINGLITERAL = 17;
  public int JJTVARNAME = 18;
  public int JJTOREXPR = 19;
  public int JJTANDEXPR = 20;
  public int JJTFLWREXPR = 21;
  public int JJTRETURN = 22;
  public int JJTQUANTIFIEDEXPR = 23;
  public int JJTSOME = 24;
  public int JJTEVERY = 25;
  public int JJTIN = 26;
  public int JJTSATISFIES = 27;
  public int JJTIFEXPR = 28;
  public int JJTIFLPAR = 29;
  public int JJTTHEN = 30;
  public int JJTELSE = 31;
  public int JJTINSTANCEOFEXPR = 32;
  public int JJTINSTANCEOF = 33;
  public int JJTCASTABLEEXPR = 34;
  public int JJTCASTABLE = 35;
  public int JJTCOMPARISONEXPR = 36;
  public int JJTRANGEEXPR = 37;
  public int JJTADDITIVEEXPR = 38;
  public int JJTMULTIPLICATIVEEXPR = 39;
  public int JJTUNARYEXPR = 40;
  public int JJTMINUS = 41;
  public int JJTPLUS = 42;
  public int JJTUNIONEXPR = 43;
  public int JJTINTERSECTEXCEPTEXPR = 44;
  public int JJTPATHEXPR = 45;
  public int JJTSTEPEXPR = 46;
  public int JJTSIMPLEFORCLAUSE = 47;
  public int JJTVALIDATEEXPR = 48;
  public int JJTVALIDATELBRACE = 49;
  public int JJTVALIDATECONTEXT = 50;
  public int JJTLBRACEEXPRENCLOSURE = 51;
  public int JJTRBRACE = 52;
  public int JJTCASTEXPR = 53;
  public int JJTCASTAS = 54;
  public int JJTTREATEXPR = 55;
  public int JJTTREATAS = 56;
  public int JJTAXISDESCENDANT = 57;
  public int JJTAXISSELF = 58;
  public int JJTAXISDESCENDANTORSELF = 59;
  public int JJTAXISFOLLOWINGSIBLING = 60;
  public int JJTAXISFOLLOWING = 61;
  public int JJTAXISNAMESPACE = 62;
  public int JJTAXISPARENT = 63;
  public int JJTAXISANCESTOR = 64;
  public int JJTAXISPRECEDINGSIBLING = 65;
  public int JJTAXISPRECEDING = 66;
  public int JJTAXISANCESTORORSELF = 67;
  public int JJTNODETEST = 68;
  public int JJTNAMETEST = 69;
  public int JJTQNAME = 70;
  public int JJTSTAR = 71;
  public int JJTNCNAMECOLONSTAR = 72;
  public int JJTSTARCOLONNCNAME = 73;
  public int JJTKINDTEST = 74;
  public int JJTPROCESSINGINSTRUCTIONTEST = 75;
  public int JJTCOMMENTTEST = 76;
  public int JJTTEXTTEST = 77;
  public int JJTANYKINDTEST = 78;
  public int JJTDOT = 79;
  public int JJTDOTDOT = 80;
  public int JJTPREDICATES = 81;
  public int JJTLBRACK = 82;
  public int JJTRBRACK = 83;
  public int JJTINTEGERLITERAL = 84;
  public int JJTDECIMALLITERAL = 85;
  public int JJTDOUBLELITERAL = 86;
  public int JJTFUNCTIONCALL = 87;
  public int JJTSCHEMACONTEXT = 88;
  public int JJTINCONTEXT = 89;
  public int JJTSCHEMAGLOBALCONTEXT = 90;
  public int JJTTYPEQNAME = 91;
  public int JJTSCHEMACONTEXTSTEP = 92;
  public int JJTSINGLETYPE = 93;
  public int JJTQMARK = 94;
  public int JJTSEQUENCETYPE = 95;
  public int JJTEMPTY = 96;
  public int JJTITEMTYPE = 97;
  public int JJTELEMENTTYPE = 98;
  public int JJTATTRIBUTETYPE = 99;
  public int JJTNODE = 100;
  public int JJTPROCESSINGINSTRUCTION = 101;
  public int JJTCOMMENT = 102;
  public int JJTTEXT = 103;
  public int JJTDOCUMENT = 104;
  public int JJTITEM = 105;
  public int JJTUNTYPED = 106;
  public int JJTATOMICVALUE = 107;
  public int JJTELEMORATTRTYPE = 108;
  public int JJTSCHEMATYPE = 109;
  public int JJTOFTYPE = 110;
  public int JJTATOMICTYPE = 111;
  public int JJTOCCURRENCEINDICATOR = 112;
  public int JJTMULTIPLY = 113;


  public String[] jjtNodeName = {
    "XPath2",
    "MatchPattern",
    "XPath",
    "ExprSequence",
    "Pattern",
    "PathPattern",
    "Root",
    "RootDescendants",
    "Slash",
    "SlashSlash",
    "void",
    "PatternStep",
    "AxisChild",
    "AxisAttribute",
    "At",
    "IdKeyPattern",
    "QNameLpar",
    "StringLiteral",
    "VarName",
    "OrExpr",
    "AndExpr",
    "FLWRExpr",
    "Return",
    "QuantifiedExpr",
    "Some",
    "Every",
    "In",
    "Satisfies",
    "IfExpr",
    "IfLpar",
    "Then",
    "Else",
    "InstanceofExpr",
    "Instanceof",
    "CastableExpr",
    "Castable",
    "ComparisonExpr",
    "RangeExpr",
    "AdditiveExpr",
    "MultiplicativeExpr",
    "UnaryExpr",
    "Minus",
    "Plus",
    "UnionExpr",
    "IntersectExceptExpr",
    "PathExpr",
    "StepExpr",
    "SimpleForClause",
    "ValidateExpr",
    "ValidateLbrace",
    "ValidateContext",
    "LbraceExprEnclosure",
    "Rbrace",
    "CastExpr",
    "CastAs",
    "TreatExpr",
    "TreatAs",
    "AxisDescendant",
    "AxisSelf",
    "AxisDescendantOrSelf",
    "AxisFollowingSibling",
    "AxisFollowing",
    "AxisNamespace",
    "AxisParent",
    "AxisAncestor",
    "AxisPrecedingSibling",
    "AxisPreceding",
    "AxisAncestorOrSelf",
    "NodeTest",
    "NameTest",
    "QName",
    "Star",
    "NCNameColonStar",
    "StarColonNCName",
    "KindTest",
    "ProcessingInstructionTest",
    "CommentTest",
    "TextTest",
    "AnyKindTest",
    "Dot",
    "DotDot",
    "Predicates",
    "Lbrack",
    "Rbrack",
    "IntegerLiteral",
    "DecimalLiteral",
    "DoubleLiteral",
    "FunctionCall",
    "SchemaContext",
    "InContext",
    "SchemaGlobalContext",
    "TypeQName",
    "SchemaContextStep",
    "SingleType",
    "QMark",
    "SequenceType",
    "Empty",
    "ItemType",
    "ElementType",
    "AttributeType",
    "Node",
    "ProcessingInstruction",
    "Comment",
    "Text",
    "Document",
    "Item",
    "Untyped",
    "AtomicValue",
    "ElemOrAttrType",
    "SchemaType",
    "OfType",
    "AtomicType",
    "OccurrenceIndicator",
    "Multiply",
  };
}
