/* Generated By:JJTree: Do not edit this line. E:/ast/xslt20/xpath_rwapi/src/org/apache/xpath/rwapi/impl/parser\XPathVisitor.java */

package org.apache.xpath.rwapi.impl.parser;

public interface XPathVisitor
{
  public Object visit(SimpleNode node, Object data);
}
