/* Generated By:JJTree: Do not edit this line. F:/projets/xpath-api/xpath_rwapi/src2/org/apache/xpath/impl/parser\XPathTreeConstants.java */

package org.apache.xpath.impl.parser;

public interface XPathTreeConstants
{
  public int JJTXPATH2 = 0;
  public int JJTMATCHPATTERN = 1;
  public int JJTXPATH = 2;
  public int JJTEXPR = 3;
  public int JJTPATTERN = 4;
  public int JJTPATHPATTERN = 5;
  public int JJTROOT = 6;
  public int JJTROOTDESCENDANTS = 7;
  public int JJTSLASHSLASH = 8;
  public int JJTVOID = 9;
  public int JJTPATTERNSTEP = 10;
  public int JJTAXISCHILD = 11;
  public int JJTAXISATTRIBUTE = 12;
  public int JJTAT = 13;
  public int JJTIDKEYPATTERN = 14;
  public int JJTIDLPAR = 15;
  public int JJTKEYLPAR = 16;
  public int JJTSTRINGLITERAL = 17;
  public int JJTVARNAME = 18;
  public int JJTFOREXPR = 19;
  public int JJTRETURN = 20;
  public int JJTIN = 21;
  public int JJTQUANTIFIEDEXPR = 22;
  public int JJTSOME = 23;
  public int JJTEVERY = 24;
  public int JJTSATISFIES = 25;
  public int JJTIFEXPR = 26;
  public int JJTOREXPR = 27;
  public int JJTANDEXPR = 28;
  public int JJTINSTANCEOFEXPR = 29;
  public int JJTTREATEXPR = 30;
  public int JJTCASTABLEEXPR = 31;
  public int JJTCASTEXPR = 32;
  public int JJTCOMPARISONEXPR = 33;
  public int JJTRANGEEXPR = 34;
  public int JJTADDITIVEEXPR = 35;
  public int JJTMULTIPLICATIVEEXPR = 36;
  public int JJTUNARYEXPR = 37;
  public int JJTUNARYMINUS = 38;
  public int JJTUNARYPLUS = 39;
  public int JJTUNIONEXPR = 40;
  public int JJTINTERSECTEXCEPTEXPR = 41;
  public int JJTPATHEXPR = 42;
  public int JJTSTEPEXPR = 43;
  public int JJTDOT = 44;
  public int JJTPREDICATES = 45;
  public int JJTDOTDOT = 46;
  public int JJTAXISDESCENDANT = 47;
  public int JJTAXISSELF = 48;
  public int JJTAXISDESCENDANTORSELF = 49;
  public int JJTAXISFOLLOWINGSIBLING = 50;
  public int JJTAXISFOLLOWING = 51;
  public int JJTAXISNAMESPACE = 52;
  public int JJTAXISPARENT = 53;
  public int JJTAXISANCESTOR = 54;
  public int JJTAXISPRECEDINGSIBLING = 55;
  public int JJTAXISPRECEDING = 56;
  public int JJTAXISANCESTORORSELF = 57;
  public int JJTNODETEST = 58;
  public int JJTNAMETEST = 59;
  public int JJTQNAME = 60;
  public int JJTSTAR = 61;
  public int JJTNCNAMECOLONSTAR = 62;
  public int JJTSTARCOLONNCNAME = 63;
  public int JJTINTEGERLITERAL = 64;
  public int JJTDECIMALLITERAL = 65;
  public int JJTDOUBLELITERAL = 66;
  public int JJTFUNCTIONCALL = 67;
  public int JJTQNAMELPAR = 68;
  public int JJTSINGLETYPE = 69;
  public int JJTOCCURRENCEZEROORONE = 70;
  public int JJTSEQUENCETYPE = 71;
  public int JJTEMPTY = 72;
  public int JJTQNAMEFORSEQUENCETYPE = 73;
  public int JJTITEM = 74;
  public int JJTELEMENTTEST = 75;
  public int JJTELEMENTTYPE = 76;
  public int JJTELEMENTTYPEFORKINDTEST = 77;
  public int JJTELEMENTTYPEFORDOCUMENTTEST = 78;
  public int JJTNILLABLE = 79;
  public int JJTATTRIBUTETEST = 80;
  public int JJTATTRIBUTETYPE = 81;
  public int JJTPITEST = 82;
  public int JJTNCNAMEFORPI = 83;
  public int JJTSTRINGLITERALFORKINDTEST = 84;
  public int JJTDOCUMENTTEST = 85;
  public int JJTCOMMENTTEST = 86;
  public int JJTTEXTTEST = 87;
  public int JJTANYKINDTEST = 88;
  public int JJTSCHEMACONTEXTPATH = 89;
  public int JJTSCHEMAGLOBALCONTEXTSLASH = 90;
  public int JJTSCHEMACONTEXTSTEPSLASH = 91;
  public int JJTLOCALNAME = 92;
  public int JJTQNAMEFORITEMTYPE = 93;
  public int JJTNODENAME = 94;
  public int JJTANYNAME = 95;
  public int JJTTYPENAME = 96;
  public int JJTOCCURRENCEZEROORMORE = 97;
  public int JJTOCCURRENCEONEORMORE = 98;


  public String[] jjtNodeName = {
    "XPath2",
    "MatchPattern",
    "XPath",
    "Expr",
    "Pattern",
    "PathPattern",
    "Root",
    "RootDescendants",
    "SlashSlash",
    "void",
    "PatternStep",
    "AxisChild",
    "AxisAttribute",
    "At",
    "IdKeyPattern",
    "IDLpar",
    "KeyLpar",
    "StringLiteral",
    "VarName",
    "ForExpr",
    "Return",
    "In",
    "QuantifiedExpr",
    "Some",
    "Every",
    "Satisfies",
    "IfExpr",
    "OrExpr",
    "AndExpr",
    "InstanceofExpr",
    "TreatExpr",
    "CastableExpr",
    "CastExpr",
    "ComparisonExpr",
    "RangeExpr",
    "AdditiveExpr",
    "MultiplicativeExpr",
    "UnaryExpr",
    "UnaryMinus",
    "UnaryPlus",
    "UnionExpr",
    "IntersectExceptExpr",
    "PathExpr",
    "StepExpr",
    "Dot",
    "Predicates",
    "DotDot",
    "AxisDescendant",
    "AxisSelf",
    "AxisDescendantOrSelf",
    "AxisFollowingSibling",
    "AxisFollowing",
    "AxisNamespace",
    "AxisParent",
    "AxisAncestor",
    "AxisPrecedingSibling",
    "AxisPreceding",
    "AxisAncestorOrSelf",
    "NodeTest",
    "NameTest",
    "QName",
    "Star",
    "NCNameColonStar",
    "StarColonNCName",
    "IntegerLiteral",
    "DecimalLiteral",
    "DoubleLiteral",
    "FunctionCall",
    "QNameLpar",
    "SingleType",
    "OccurrenceZeroOrOne",
    "SequenceType",
    "Empty",
    "QNameForSequenceType",
    "Item",
    "ElementTest",
    "ElementType",
    "ElementTypeForKindTest",
    "ElementTypeForDocumentTest",
    "Nillable",
    "AttributeTest",
    "AttributeType",
    "PITest",
    "NCNameForPI",
    "StringLiteralForKindTest",
    "DocumentTest",
    "CommentTest",
    "TextTest",
    "AnyKindTest",
    "SchemaContextPath",
    "SchemaGlobalContextSlash",
    "SchemaContextStepSlash",
    "LocalName",
    "QNameForItemType",
    "NodeName",
    "AnyName",
    "TypeName",
    "OccurrenceZeroOrMore",
    "OccurrenceOneOrMore",
  };
}
