/* Generated By:JJTree: Do not edit this line. F:/projets/xpath-api/xpath_rwapi/src2/org/apache/xpath/impl/parser\XPathVisitor.java */

package org.apache.xpath.impl.parser;

public interface XPathVisitor
{
  public Object visit(SimpleNode node, Object data);
}
