/* Generated By:JJTree: Do not edit this line. F:/xalan3/xml-xalan/java/xpath-src\XPathVisitor.java */

package org.apache.xpath.parser;

public interface XPathVisitor
{
  public Object visit(SimpleNode node, Object data);
}
