/* Generated By:JJTree: Do not edit this line. C:/data/projects/xml-xalan-xslt20/java/xpath_rwapi/src2/org/apache/xpath/impl/parser\XPathTreeConstants.java */

package org.apache.xpath.impl.parser;

public interface XPathTreeConstants
{
  public int JJTXPATH2 = 0;
  public int JJTMATCHPATTERN = 1;
  public int JJTXPATH = 2;
  public int JJTEXPRSEQUENCE = 3;
  public int JJTPATTERN = 4;
  public int JJTPATHPATTERN = 5;
  public int JJTROOT = 6;
  public int JJTROOTDESCENDANTS = 7;
  public int JJTSLASHSLASH = 8;
  public int JJTVOID = 9;
  public int JJTPATTERNSTEP = 10;
  public int JJTAXISCHILD = 11;
  public int JJTAXISATTRIBUTE = 12;
  public int JJTAT = 13;
  public int JJTIDKEYPATTERN = 14;
  public int JJTQNAMELPAR = 15;
  public int JJTSTRINGLITERAL = 16;
  public int JJTVARNAME = 17;
  public int JJTOREXPR = 18;
  public int JJTANDEXPR = 19;
  public int JJTFLWREXPR = 20;
  public int JJTRETURN = 21;
  public int JJTQUANTIFIEDEXPR = 22;
  public int JJTSOME = 23;
  public int JJTEVERY = 24;
  public int JJTIN = 25;
  public int JJTSATISFIES = 26;
  public int JJTIFEXPR = 27;
  public int JJTINSTANCEOFEXPR = 28;
  public int JJTCASTABLEEXPR = 29;
  public int JJTCASTABLE = 30;
  public int JJTCOMPARISONEXPR = 31;
  public int JJTRANGEEXPR = 32;
  public int JJTADDITIVEEXPR = 33;
  public int JJTMULTIPLICATIVEEXPR = 34;
  public int JJTUNARYEXPR = 35;
  public int JJTMINUS = 36;
  public int JJTPLUS = 37;
  public int JJTUNIONEXPR = 38;
  public int JJTINTERSECTEXCEPTEXPR = 39;
  public int JJTPATHEXPR = 40;
  public int JJTSTEPEXPR = 41;
  public int JJTVALIDATEEXPR = 42;
  public int JJTVALIDATELBRACE = 43;
  public int JJTVALIDATECONTEXT = 44;
  public int JJTSLASH = 45;
  public int JJTLBRACEEXPRENCLOSURE = 46;
  public int JJTRBRACE = 47;
  public int JJTCASTEXPR = 48;
  public int JJTCASTAS = 49;
  public int JJTTREATEXPR = 50;
  public int JJTTREATAS = 51;
  public int JJTAXISDESCENDANT = 52;
  public int JJTAXISSELF = 53;
  public int JJTAXISDESCENDANTORSELF = 54;
  public int JJTAXISFOLLOWINGSIBLING = 55;
  public int JJTAXISFOLLOWING = 56;
  public int JJTAXISNAMESPACE = 57;
  public int JJTAXISPARENT = 58;
  public int JJTAXISANCESTOR = 59;
  public int JJTAXISPRECEDINGSIBLING = 60;
  public int JJTAXISPRECEDING = 61;
  public int JJTAXISANCESTORORSELF = 62;
  public int JJTNODETEST = 63;
  public int JJTNAMETEST = 64;
  public int JJTQNAME = 65;
  public int JJTSTAR = 66;
  public int JJTNCNAMECOLONSTAR = 67;
  public int JJTSTARCOLONNCNAME = 68;
  public int JJTPROCESSINGINSTRUCTIONTEST = 69;
  public int JJTCOMMENTTEST = 70;
  public int JJTTEXTTEST = 71;
  public int JJTANYKINDTEST = 72;
  public int JJTDOT = 73;
  public int JJTDOTDOT = 74;
  public int JJTPREDICATES = 75;
  public int JJTINTEGERLITERAL = 76;
  public int JJTDECIMALLITERAL = 77;
  public int JJTDOUBLELITERAL = 78;
  public int JJTFUNCTIONCALL = 79;
  public int JJTSCHEMACONTEXT = 80;
  public int JJTINCONTEXT = 81;
  public int JJTSCHEMAGLOBALCONTEXT = 82;
  public int JJTTYPEQNAME = 83;
  public int JJTSCHEMACONTEXTSTEP = 84;
  public int JJTSINGLETYPE = 85;
  public int JJTQMARK = 86;
  public int JJTSEQUENCETYPE = 87;
  public int JJTEMPTY = 88;
  public int JJTELEMENTTYPE = 89;
  public int JJTATTRIBUTETYPE = 90;
  public int JJTNODE = 91;
  public int JJTPROCESSINGINSTRUCTION = 92;
  public int JJTCOMMENT = 93;
  public int JJTTEXT = 94;
  public int JJTDOCUMENT = 95;
  public int JJTITEM = 96;
  public int JJTUNTYPED = 97;
  public int JJTATOMICVALUE = 98;
  public int JJTELEMORATTRTYPE = 99;
  public int JJTSCHEMATYPE = 100;
  public int JJTOFTYPE = 101;
  public int JJTATOMICTYPE = 102;
  public int JJTMULTIPLY = 103;


  public String[] jjtNodeName = {
    "XPath2",
    "MatchPattern",
    "XPath",
    "ExprSequence",
    "Pattern",
    "PathPattern",
    "Root",
    "RootDescendants",
    "SlashSlash",
    "void",
    "PatternStep",
    "AxisChild",
    "AxisAttribute",
    "At",
    "IdKeyPattern",
    "QNameLpar",
    "StringLiteral",
    "VarName",
    "OrExpr",
    "AndExpr",
    "FLWRExpr",
    "Return",
    "QuantifiedExpr",
    "Some",
    "Every",
    "In",
    "Satisfies",
    "IfExpr",
    "InstanceofExpr",
    "CastableExpr",
    "Castable",
    "ComparisonExpr",
    "RangeExpr",
    "AdditiveExpr",
    "MultiplicativeExpr",
    "UnaryExpr",
    "Minus",
    "Plus",
    "UnionExpr",
    "IntersectExceptExpr",
    "PathExpr",
    "StepExpr",
    "ValidateExpr",
    "ValidateLbrace",
    "ValidateContext",
    "Slash",
    "LbraceExprEnclosure",
    "Rbrace",
    "CastExpr",
    "CastAs",
    "TreatExpr",
    "TreatAs",
    "AxisDescendant",
    "AxisSelf",
    "AxisDescendantOrSelf",
    "AxisFollowingSibling",
    "AxisFollowing",
    "AxisNamespace",
    "AxisParent",
    "AxisAncestor",
    "AxisPrecedingSibling",
    "AxisPreceding",
    "AxisAncestorOrSelf",
    "NodeTest",
    "NameTest",
    "QName",
    "Star",
    "NCNameColonStar",
    "StarColonNCName",
    "ProcessingInstructionTest",
    "CommentTest",
    "TextTest",
    "AnyKindTest",
    "Dot",
    "DotDot",
    "Predicates",
    "IntegerLiteral",
    "DecimalLiteral",
    "DoubleLiteral",
    "FunctionCall",
    "SchemaContext",
    "InContext",
    "SchemaGlobalContext",
    "TypeQName",
    "SchemaContextStep",
    "SingleType",
    "QMark",
    "SequenceType",
    "Empty",
    "ElementType",
    "AttributeType",
    "Node",
    "ProcessingInstruction",
    "Comment",
    "Text",
    "Document",
    "Item",
    "Untyped",
    "AtomicValue",
    "ElemOrAttrType",
    "SchemaType",
    "OfType",
    "AtomicType",
    "Multiply",
  };
}
